apiVersion: v1
kind: Namespace
metadata:
  name: app-ingress
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gemini
  annotations:
    konghq.com/plugins: ai-proxy-gemini
    konghq.com/tags: "ai-manager-name: Gemini Gateway API, ai-manager-created"
  name: gemini
  namespace: app-ingress
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 1027
  selector:
    app: gemini
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gemini
  name: gemini
  namespace: app-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini
  template:
    metadata:
      labels:
        app: gemini
    spec:
      containers:
        - image: kong/go-echo:latest
          name: gemini
          ports:
            - containerPort: 1027 # HTTP
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ai-proxy-gemini
  namespace: app-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/tags: "ai-manager-plugin-for: ai-manager-name: Gemini Gateway API"
plugin: ai-proxy-advanced
config:
  balancer:
    retries: 5
    hash_on_header: X-Kong-LLM-Request-ID
    algorithm: round-robin
    latency_strategy: tpot
  model_name_header: true          
  targets:
    - model:
        name: gemini-2.5-flash
        options:
          max_tokens: 4096
          temperature: 1
          input_cost:  0.30
          output_cost: 2.50
        provider: gemini
      auth:
        param_location: query
        param_name: key
        param_value: "***TO_BE_REPLACED***"
      logging:
        log_payloads: true
        log_statistics: true
      route_type: llm/v1/chat
    - model:
        name: gemini-2.5-pro
        options:
          max_tokens: 4096
          temperature: 1
          input_cost:  1.25
          output_cost: 10.00
        provider: gemini
      auth:
        param_location: query
        param_name: key
        param_value: "***TO_BE_REPLACED***"
      logging:
        log_payloads: true
        log_statistics: true
      route_type: llm/v1/chat
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gemini-route
  namespace: app-ingress
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/tags: "ai-manager-route-for: ai-manager-name: Gemini Gateway API"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kong
      namespace: kong-ingress
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /gemini/api/v1
          headers:
            - name: x-llm
              type: Exact
              value: gemini4
      backendRefs:
        - name: gemini
          port: 80